[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "atk",
  "atk-bridge",
  "cups",
  "libdrm",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "libxkbcommon",
  "pango",
  "cairo",
  "glib",
  "expat"
]